---
name: 🗺️ Chart Lint

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  chart-lint:
    name: Chart Lint
    permissions:
      contents: read
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-chart-lint.yml@aa8abd093cd24a89b8dd2d76b6733d8121c64c52 # v8.0.3
